
CREATE TABLE user(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL
);

CREATE TABLE category(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE comment(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    content varchar(250) NOT NULL,
    date DATE NOT NULL,
    user_id INT NOT NULL,
    CONSTRAINT FK_USER_COMMENT FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE article(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    date DATE NOT NULL,
    content VARCHAR(250) NOT NULL,
    category_id INT,
    comment_id INT,
    user_id INT,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT FK_COMMENT FOREIGN KEY (comment_id) REFERENCES comment(id),
    CONSTRAINT FK_USER_ARTICLE FOREIGN KEY (user_id) REFERENCES user(id)
);